[package]
name = "noname"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#irc = "0.13"
irc = "0.15"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
